### PR TITLE
Allow saving in singleplayer survival

### PR DESCRIPTION
**Pull request by return-true-if-false**
Addresses / Implement #8 (Allow Item Editor in Survival)

### CODE REVIEW

**Comment by prokube** [comment]
time to get banned from mineland

**Comment by return-true-if-false** [comment]
How do you intend to get banned because of this feature?

**Comment by Ruukas97** [comment]
> time to get banned from mineland
> 

It will just allow survival saving in singleplayer.

**Review by Ruukas97 — APPROVED** [review]
Nice, good job! :)

**Pull request merged**
